### ISSUE TITLE
模拟器启动失败

### ISSUE THREAD

**Issue by SuperLeven** [Tencent/tdesign-miniprogram-starter-retail#109]
### tdesign-miniprogram-starter-retail 版本

1.0.0

### 实际结果

[ pages/home/home.json 文件内容错误] pages/home/home.json: ["usingComponents"]["t-search"]: "tdesign-miniprogram/search/search" 未找到(env: macOS,mp,1.06.2307250; lib: 2.23.1)

**Comment by jumodada** [comment]
微信小程序里面- 工具-构建npm，就可以运行了
