### ISSUE TITLE
可以用这份设计稿子去开课教学吗

### ISSUE THREAD

**Issue by wakaryry** [Tencent/tdesign-miniprogram-starter-retail#48]
### 这个功能解决了什么问题

想开课讲一些vue3的课程，可以使用这个仓库里面的设计稿去用vue3实现，然后开课吗？

### 你建议的方案是什么

希望得到授权允许。谢谢。

**Comment by AvenirZheng** [comment]
可以

**Comment by wakaryry** [comment]
谢谢。到时我会说明设计稿子来源于这个仓库地址。
