### ISSUE TITLE
[步进器]iOS端小程序Demo购物车的步进器 + 和 - 上下没有居中对齐。

### ISSUE THREAD

**Issue by dufu1991** [Tencent/tdesign-miniprogram-starter-retail#63]
### tdesign-miniprogram-starter-retail 版本

我看的就是最新版本

### 重现链接

无

### 重现步骤

无

### 期望结果

iOS端小程序Demo购物车的步进器 + 和 - 上下居中对齐。

### 实际结果

iOS端小程序Demo购物车的步进器 + 和 - 上下没有居中对齐。

### 框架版本

小程序Demo

### 浏览器版本

微信版本8.0.31

### 系统版本

iOS16

### Node版本

无

### 补充说明

iOS端小程序Demo购物车的步进器 + 和 - 上下没有居中对齐。

**Comment by anlyyao** [comment]
@dufu1991  
是居中的吧？
机型: 13pro
![WechatIMG13201](https://user-images.githubusercontent.com/51158141/211754988-e8625ff7-3890-480f-bc37-1c531a72b349.jpeg)

**Comment by dufu1991** [comment]
我的机型也是13Pro，没有上下居中。
![IMG_1480](https://user-images.githubusercontent.com/24769077/211756184-2e9bf5e9-c852-45f8-855b-a69dc488371a.jpg)

**Comment by LeeJim** [comment]
> 我的机型也是13Pro，没有上下居中。 ![IMG_1480](https://user-images.githubusercontent.com/24769077/211756184-2e9bf5e9-c852-45f8-855b-a69dc488371a.jpg)

应该是版本问题，请问你组件库是什么版本？
